name: Build, publish and deploy to MonsterASP.NET
on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Install dependencies
        run: cd RegMan.Backend.API && dotnet restore

      - name: Build
        run: cd RegMan.Backend.API && dotnet build --configuration Release --no-restore

      - name: Publish
        run: cd RegMan.Backend.API && dotnet publish --configuration Release --output ./publish --runtime win-x86 --self-contained false

      - name: List published files
        run: Get-ChildItem -Recurse "RegMan.Backend.API/publish/" | Select-Object FullName
        shell: pwsh

      - name: Update appsettings with connection string
        run: |
          $appSettings = Get-Content "RegMan.Backend.API/publish/appsettings.json" | ConvertFrom-Json
          $appSettings.ConnectionStrings.DefaultConnection = "${{ secrets.CONNECTION_STRING }}"
          $appSettings | ConvertTo-Json -Depth 10 | Set-Content "RegMan.Backend.API/publish/appsettings.json"
        shell: pwsh

      - name: Test with .NET
        run: cd RegMan.Backend.API && dotnet test

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: 'RegMan.Backend.API/publish/'