name: Build, publish and deploy to MonsterASP.NET

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    env:
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    runs-on: windows-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Setup .NET 8
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restore
      - name: Restore dependencies
        run: cd RegMan.Backend.API && dotnet restore

      # Build
      - name: Build
        run: cd RegMan.Backend.API && dotnet build --configuration Release --no-restore

      # Publish
      - name: Publish
        run: cd RegMan.Backend.API && dotnet publish --configuration Release --output ./publish --runtime win-x86 --self-contained false

      # Inject Connection String
      - name: Inject Connection String
        shell: pwsh
        run: |
          $path = "RegMan.Backend.API/publish/appsettings.json"
          $json = Get-Content $path | ConvertFrom-Json

          if (-not $json.ConnectionStrings) {
            $json | Add-Member -MemberType NoteProperty -Name ConnectionStrings -Value @{}
          }

          $json.ConnectionStrings.DefaultConnection = "${{ secrets.CONNECTION_STRING }}"
          $json | ConvertTo-Json -Depth 10 | Set-Content $path

      # Inject Admin Credentials (TEMP)
      - name: Inject Admin Credentials
        shell: pwsh
        run: |
          $path = "RegMan.Backend.API/publish/appsettings.json"
          $json = Get-Content $path | ConvertFrom-Json

          if (-not $json.Admin) {
            $json | Add-Member -MemberType NoteProperty -Name Admin -Value @{}
          }

          $json.Admin.Email = "${{ secrets.ADMIN_EMAIL }}"
          $json.Admin.Password = "${{ secrets.ADMIN_PASSWORD }}"

          $json | ConvertTo-Json -Depth 10 | Set-Content $path

      # Deploy to MonsterASP.NET
      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: "RegMan.Backend.API/publish/"
